Group 5
allegheny-computer-science-203-s2021/assessment pull request #4
Opened 2021-03-04 22:13 UTC by ColemanKobe

This adds guidelines to two skills: formatting with black in the "Software Development with Python" section and software testing in the "Foundations of Software Engineering" section. These sections are in assessments.md

2021-03-04 23:40 UTC, noorbuchi requested changes

2021-03-04 23:40 UTC, noorbuchi commented on assessment.md
> +    this skill.
These points are exactly the same as the ones present in #3. I think that we should only include them in one PR and make sure that all edits to them are being done in one branch. I would like to hear the PR contributors' reasons for including them here as well.

2021-03-04 23:44 UTC, Nathandloria approved these changes

2021-03-05 03:01 UTC, noorbuchi approved these changes
Looks good!

2021-03-05 03:08 UTC, corlettim approved these changes

2021-03-05 15:27 UTC, jjumadinova approved these changes

2021-03-05 18:29 UTC, merged