Group 1
allegheny-computer-science-203-s2021/assessment pull request #8
Opened 2021-03-15 19:43 UTC by kemandel

Created descriptions for the first five assessments under Software Development with Python.

2021-03-15 20:27 UTC, enpuyou requested changes
Hi members of group 1, I'm mostly fine with the proposed assessments. Just one issue: the emoji used in the assessment document is the [markdown version](https://github.com/ikatyang/emoji-cheat-sheet) instead of the actual emoji icon. You can also find that in the `Assessment Key` section. Thanks.

2021-03-15 20:35 UTC, kemandel reviewed
Changed emojis to the markdown format.

2021-03-15 20:37 UTC, enpuyou approved these changes

2021-03-15 20:37 UTC, noorbuchi approved these changes
Looks good!

2021-03-16 04:30 UTC, jjumadinova approved these changes

2021-03-16 04:30 UTC, merged